In [2]:
from pathlib import Path
import pandas as pd

dataDir = Path("data")
csvFiles = sorted(dataDir.glob("*.csv"))

columns = [
    "transaction_id",
    "price",
    "date_of_transfer",
    "postcode",
    "property_type",
    "new_build",
    "duration",
    "paon",
    "saon",
    "street",
    "locality",
    "town_city",
    "district",
    "county",
    "ppd_category",
    "record_status",
]

dfs = [
    pd.read_csv(f, header=None, names=columns)
    for f in csvFiles
]

allYears = pd.concat(dfs, ignore_index=True)

# Clean types
allYears["date_of_transfer"] = pd.to_datetime(allYears["date_of_transfer"])
allYears["price"] = pd.to_numeric(allYears["price"])

allYears.head()

,transaction_id,price,date_of_transfer,postcode,property_type,new_build,duration,paon,saon,street,locality,town_city,district,county,ppd_category,record_status
0,{75050A85-7FB9-9A88-E053-6B04A8C02390},137196,2018-05-25,LE12 6XT,S,Y,F,29,NaN,PEACOCK GARDENS,EAST LEAKE,LOUGHBOROUGH,RUSHCLIFFE,NOTTINGHAMSHIRE,A,A
1,{75050A85-7FBA-9A88-E053-6B04A8C02390},229995,2018-06-29,NG21 9GT,D,Y,F,7,NaN,CHAFFINCH CLOSE,CLIPSTONE VILLAGE,MANSFIELD,NEWARK AND SHERWOOD,NOTTINGHAMSHIRE,A,A
2,{75050A85-7FBB-9A88-E053-6B04A8C02390},175000,2018-07-06,NG19 7EW,D,N,F,18A,NaN,BEECH HILL CRESCENT,NaN,MANSFIELD,MANSFIELD,NOTTINGHAMSHIRE,A,A
3,{75050A85-7FBC-9A88-E053-6B04A8C02390},211995,2018-06-28,S81 7TB,S,Y,F,2,NaN,RED ADMIRAL ROAD,NaN,WORKSOP,BASSETLAW,NOTTINGHAMSHIRE,A,A
4,{75050A85-7FBE-9A88-E053-6B04A8C02390},194995,2018-06-29,LE12 6XT,T,Y,F,15,NaN,PEACOCK GARDENS,EAST LEAKE,LOUGHBOROUGH,RUSHCLIFFE,NOTTINGHAMSHIRE,A,A

In [3]:
allYears.shape

(2945773, 16)

In [4]:
allYears.isna().sum().sort_values(ascending=False).head()

saon             2553374
locality         1814223
street             56875
postcode           12978
property_type          0
dtype: int64

In [5]:
allYears.describe()

              price               date_of_transfer
count  2.945773e+06                        2945773
mean   3.608515e+05  2019-06-28 07:52:47.839611904
min    1.000000e+00            2018-01-01 00:00:00
25%    1.500000e+05            2018-09-27 00:00:00
50%    2.350000e+05            2019-06-24 00:00:00
75%    3.665000e+05            2020-03-10 00:00:00
max    5.692000e+08            2020-12-31 00:00:00
std    1.871548e+06                            NaN